### ISSUE TITLE
test

### ISSUE THREAD

**Issue by acamposruiz** [acamposruiz/api.lobupla2#1]
**Summary**

This is a fix for this issue

When running a single test that has many test cases the error messages are printed before the list of failing/passing tests which makes us to scroll up every time just to see the error message.

This Pull Request change the behavior of print error messages to put them after the list of tests

So the behavior is going to switch from the actual:

![image](https://user-images.githubusercontent.com/2551046/30125866-312bed7c-933a-11e7-8110-0946090d4c1e.png)

to this:

![image](https://user-images.githubusercontent.com/2551046/30125656-64c2f0dc-9339-11e7-9c66-e20dd8c72ee3.png)

In order to keep the messages consistent, Both the FAIL and PASS messages will be printed after the list of failing/passing tests.

So this:

![image](https://user-images.githubusercontent.com/2551046/30126180-715da132-933b-11e7-934d-4523e42607b4.png)

will also switch to:

![image](https://user-images.githubusercontent.com/2551046/30126246-aef9cac0-933b-11e7-90eb-53485ad4a80f.png)
 

**Test plan**

**Comment by acamposruiz** [comment]
getMockImplementation
      ✓ should mock calls to a mock function (24ms)
    mockImplementationOnce
      ✓ should mock single call to a mock function (26ms)
      ✓ should fallback to default mock function when no specific mock is available (25ms)
    spyOn
      ✓ should work (30ms)
      ✓ should throw on invalid input (25ms)
      ✓ supports restoring all spies (25ms)
    stub()
      ✕ encountered a declaration exception (27ms)

 FAIL  packages/jest-mock/src/__tests__/jest_mock.test.js
  ● moduleMocker › stub() › encountered a declaration exception

    expect(received).toBe(expected)

    Expected value to be (using ===):
      false
    Received:
      true

      at Object.it (packages/jest-mock/src/__tests__/jest_mock.test.js:539:20)

**Comment by acamposruiz** [comment]
✓ should work (30ms)
      ✓ should throw on invalid input (25ms)
      ✓ supports restoring all spies (25ms)
    stub()
      ✕ encountered a declaration exception (27ms)

 FAIL  packages/jest-mock/src/__tests__/jest_mock.test.js
  ● moduleMocker › stub() › encountered a declaration exception

    expect(received).toBe(expected)

    Expected value to be (using ===):
      false
    Received:
      true

      at Object.it (packages/jest-mock/src/__tests__/jest_mock.test.js:539:20)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 37 passed, 38 total
Snapshots:   0 total

**Comment by acamposruiz** [comment]
✓ should work (30ms)
      ✓ should throw on invalid input (25ms)
      ✓ supports restoring all spies (25ms)
    stub()
      ✕ encountered a declaration exception (27ms)

 FAIL  packages/jest-mock/src/__tests__/jest_mock.test.js
  ● moduleMocker › stub() › encountered a declaration exception

    expect(received).toBe(expected)

    Expected value to be (using ===):
      false
    Received:
      true

      at Object.it (packages/jest-mock/src/__tests__/jest_mock.test.js:539:20)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 37 passed, 38 total
Snapshots:   0 total

**Comment by acamposruiz** [comment]
✓ should work (30ms)
      ✓ should throw on invalid input (25ms)
      ✓ supports restoring all spies (25ms)
    stub()
      ✕ encountered a declaration exception (27ms)

 FAIL  packages/jest-mock/src/__tests__/jest_mock.test.js
  ● moduleMocker › stub() › encountered a declaration exception

    expect(received).toBe(expected)

    Expected value to be (using ===):
      false
    Received:
      true

      at Object.it (packages/jest-mock/src/__tests__/jest_mock.test.js:539:20)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 37 passed, 38 total
Snapshots:   0 total

**Comment by acamposruiz** [comment]
✓ should work (30ms)
      ✓ should throw on invalid input (25ms)
      ✓ supports restoring all spies (25ms)
    stub()
      ✕ encountered a declaration exception (27ms)

 FAIL  packages/jest-mock/src/__tests__/jest_mock.test.js
  ● moduleMocker › stub() › encountered a declaration exception

    expect(received).toBe(expected)

    Expected value to be (using ===):
      false
    Received:
      true

      at Object.it (packages/jest-mock/src/__tests__/jest_mock.test.js:539:20)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 37 passed, 38 total
Snapshots:   0 total

**Comment by acamposruiz** [comment]
![image](https://user-images.githubusercontent.com/2551046/30096035-78ca5aa6-92d6-11e7-956d-3d8e3c3cf39f.png)

**Comment by ULis3h** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
yenjuu, @RiccardoBonesi, @orzmaker, @stanwolverine, @yrong, @xxlv, @cpurta, @imaksp, @0xkzam, @BobbyBriQz, @coffeefoam, @armgit5, @sruediger, @amihalopoulos, @Princey29, @liquizzz, @silvercondor, @sudheerDev, @mhdigitalweb, @HemangLunagaria
